// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: ezCaptchaPB.proto

package ezCaptchaPB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EZCaptchaServiceClient is the client API for EZCaptchaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EZCaptchaServiceClient interface {
	GetCaptcha(ctx context.Context, in *EZCaptchaEmpty, opts ...grpc.CallOption) (*EZCaptchaRsp, error)
}

type eZCaptchaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEZCaptchaServiceClient(cc grpc.ClientConnInterface) EZCaptchaServiceClient {
	return &eZCaptchaServiceClient{cc}
}

func (c *eZCaptchaServiceClient) GetCaptcha(ctx context.Context, in *EZCaptchaEmpty, opts ...grpc.CallOption) (*EZCaptchaRsp, error) {
	out := new(EZCaptchaRsp)
	err := c.cc.Invoke(ctx, "/EZCaptchaService/GetCaptcha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EZCaptchaServiceServer is the server API for EZCaptchaService service.
// All implementations must embed UnimplementedEZCaptchaServiceServer
// for forward compatibility
type EZCaptchaServiceServer interface {
	GetCaptcha(context.Context, *EZCaptchaEmpty) (*EZCaptchaRsp, error)
	mustEmbedUnimplementedEZCaptchaServiceServer()
}

// UnimplementedEZCaptchaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEZCaptchaServiceServer struct {
}

func (UnimplementedEZCaptchaServiceServer) GetCaptcha(context.Context, *EZCaptchaEmpty) (*EZCaptchaRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptcha not implemented")
}
func (UnimplementedEZCaptchaServiceServer) mustEmbedUnimplementedEZCaptchaServiceServer() {}

// UnsafeEZCaptchaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EZCaptchaServiceServer will
// result in compilation errors.
type UnsafeEZCaptchaServiceServer interface {
	mustEmbedUnimplementedEZCaptchaServiceServer()
}

func RegisterEZCaptchaServiceServer(s grpc.ServiceRegistrar, srv EZCaptchaServiceServer) {
	s.RegisterService(&EZCaptchaService_ServiceDesc, srv)
}

func _EZCaptchaService_GetCaptcha_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(EZCaptchaEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZCaptchaServiceServer).GetCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EZCaptchaService/GetCaptcha",
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(EZCaptchaServiceServer).GetCaptcha(ctx, req.(*EZCaptchaEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// EZCaptchaService_ServiceDesc is the grpc.ServiceDesc for EZCaptchaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EZCaptchaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EZCaptchaService",
	HandlerType: (*EZCaptchaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaptcha",
			Handler:    _EZCaptchaService_GetCaptcha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ezCaptchaPB.proto",
}
